#ifndef GTK2STYLEENHANCEDPLUGIN_GLOBAL_H
#define GTK2STYLEENHANCEDPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GTK2STYLEENHANCEDPLUGIN_LIBRARY)
#  define GTK2STYLEENHANCEDPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GTK2STYLEENHANCEDPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GTK2STYLEENHANCEDPLUGIN_GLOBAL_H
