#ifndef PEONYQTMENUPLUGINMATETERMINAL_GLOBAL_H
#define PEONYQTMENUPLUGINMATETERMINAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PEONYQTMENUPLUGINMATETERMINAL_LIBRARY)
#  define PEONYQTMENUPLUGINMATETERMINALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PEONYQTMENUPLUGINMATETERMINALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PEONYQTMENUPLUGINMATETERMINAL_GLOBAL_H
