.\" Man page for Peony-Qt desktop
.TH Peony-Qt 1 "09 December 2019" "UKUI Desktop Environment"
.SH "NAME"
Peony-Qt desktop \- The UKUI3.0 desktop program.
.SH "SYNOPSIS"
.B peony-qt-desktop [OPTION]
.SH "DESCRIPTION"
Peony-Qt is the default file manager for UKUI3.0. 
This is the desktop program command line tool for interaction of terminal.
.SH "OPTIONS"
.TP
\fB -q, --quit\fR
Close the desktop window, stop the running service and quit.
.TP
\fB -d, --daemon\fR
Run program with DBus service.
.TP
\fB -w, --desktop-window\fR
Show desktop window.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at:
https://github.com/explorer-cs/peony-qt/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by:
Yue Lan <lanyue@kylinos.cn> (2019)
