.\" Man page for peony-file-management-properties
.TH PEONY-FILE-MANAGEMENT-PROPERTIES 1 "29 January 2014" "UKUI Desktop Environment" "General Manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH "NAME"
Peony\-file\-management\-properties \- Peony File Management Preferences
.SH "SYNOPSIS"
.B peony\-file\-management\-properties
.SH "DESCRIPTION"
Peony File Management Properties is distributed as a part of the peony package and is used to configure Peony's preferences. It is typically accessible through the "Edit" menu in Peony browser windows, or by pressing "ALT+E" and then "N" once the menu opens.
.PP
File Management Preferences allows the user to configure the way peony behaves.
.PP
You can specify appearance preferences for the Default View; and defaults for Icon, Compact, List, and Tree View; and select sort options and display options. You can configure Peony to recognize Single or Double Click input; as well as Include a Delete command and menu option that bypasses the Trash. Peony File Management Preferences (\fBpeony-file-management-properties\fR) also allows you to tell Peony how to handle certain files; whether to View or Run executable text files; Automatically view or play Media like CDs, DVDs, or photos, and which applications to use when performing these tasks. Among some other options, this dialog also allows you to adjust file-preview settings, and settings for installed plugins if they exist.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/ukui-desktop/peony/issues
.SH "AUTHORS"
.SS This Man Page has been written for the UKUI Desktop Environment by:
Adam Erdman <hekel@archlinux.info> (2014)
.SH "SEE ALSO"
.SS
Peony documentation can be found from the "Help" menu, or by pressing the F1 key. 
Further information may also be available at: http://wiki.ukui.org/docs
.P
.BR "peony" (1),
.BR "peony-autorun-software" (1),
.BR "peony-connect-server" (1)
