.\" Man page for peony-autorun-software
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.TH PEONY-AUTORUN-SOFTWARE 1 "29 January 2014" "UKUI Desktop Environment" "General Manual"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH "NAME"
peony-autorun-software \- Autorun Software in Peony
.SH "DESCRIPTION"
This executable is provided as a part of the Peony package for the UKUI Desktop Environment.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/ukui-desktop/peony/issues
.SH "LICENSE"
GPL v2 or later
.SH "SEE ALSO"
.SS
Peony documentation can be found from the "Help" menu, or by pressing the F1 key. 
Further information may also be available at: http://wiki.ukui.org/docs
.P
.BR "peony" (1),
.BR "peony-connect-server" (1),
.BR "peony-file-management-properties" (1)
