#ifndef DIRECTORYVIEWEXTENSIONSPLUGINTEST_GLOBAL_H
#define DIRECTORYVIEWEXTENSIONSPLUGINTEST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DIRECTORYVIEWEXTENSIONSPLUGINTEST_LIBRARY)
#  define DIRECTORYVIEWEXTENSIONSPLUGINTESTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DIRECTORYVIEWEXTENSIONSPLUGINTESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DIRECTORYVIEWEXTENSIONSPLUGINTEST_GLOBAL_H
