.\" Man Page for Peony-Qt
.TH Peony-Qt 1 "December 09, 2019" "UKUI Desktop Environment"
.SH "NAME"
peony-qt \- command line binary for UKUI3.0 FileManager.
.SH "SYNOPSIS"
.B peony-qt [OPTION] [FILE1, FILE2...]
.SH "DESCRIPTION"
Peony-Qt is default FileManager of UKUI3.0.
This program provides several commands for interactions with the program.
.TP
\fB -q, --quit\fR
Close all windows and quit.
.TP
\fB -i, --show-items\fR
Show items in directories and select them.
.TP
\fB -f, --show-folders\fR
Show folders.
.TP
\fB -p, --show-properties\fR
Show files properties.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
https://github.com/explorer-cs/peony-qt/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by:
Yue Lan <lanyue@kylinos.cn> (2019)
