#ifndef PEONYQTPREVIEWFILECONTENTPLUGIN_GLOBAL_H
#define PEONYQTPREVIEWFILECONTENTPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PEONYQTPREVIEWFILECONTENTPLUGIN_LIBRARY)
#  define PEONYQTPREVIEWFILECONTENTPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PEONYQTPREVIEWFILECONTENTPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PEONYQTPREVIEWFILECONTENTPLUGIN_GLOBAL_H
