#ifndef PROPERTIESWINDOWTABPAGEPLUGINEXAMPLE_GLOBAL_H
#define PROPERTIESWINDOWTABPAGEPLUGINEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROPERTIESWINDOWTABPAGEPLUGINEXAMPLE_LIBRARY)
#  define PROPERTIESWINDOWTABPAGEPLUGINEXAMPLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROPERTIESWINDOWTABPAGEPLUGINEXAMPLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROPERTIESWINDOWTABPAGEPLUGINEXAMPLE_GLOBAL_H
