name: build

on:
  push:
    branches:
      - master

  pull_request:
    branches: 
      - master

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout peony source
      uses: actions/checkout@v2

    - name: Update apt repository
      run: sudo apt-get update -y

    - name: Install latest Qt5
      run: sudo apt-get -y install build-essential qt5-default qttools5-dev-tools

    - name: Instal dependcies
      run: sudo apt-get install -y debhelper-compat pkg-kde-tools pkg-config libglib2.0-dev libqt5x11extras5-dev  libgsettings-qt-dev libpoppler-dev libpoppler-qt5-dev libkf5windowsystem-dev qtbase5-private-dev
      
    - name: QMake generate & Make
      run: mkdir build && cd build && qmake .. && make -j$(nproc)